---
title: "Finals: Questions 3&4"
author: "Matthew Melnychuk"
date: "12/6/2021"
output: html_document 
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

If needed, download this RMarkdown [here](https://mattmelnychuk.github.io/Final_3_4.Rmd)

## Question 3: Census Density with Checkbox

```{r}
library(tidyverse)
library(shiny)

d = read_csv('adult_modified.csv')

# get variable names
variables_names = names(d)

# get names of numeric variables
variables_numeric = d %>% select_if(is.numeric) %>% names

# get names of categorical variables
variables_category = d %>% select_if(is.character) %>% names



ui <- fluidPage(
  
  titlePanel("Density Plot for Census Data"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variable",
        choices = variables_numeric, selected = "age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variable",
        choices = variables_category,
        selected = "sex"
      ),
      
      checkboxGroupInput(inputId = "native__country", label = "Select Native Country",
                         choices = names(table(d$native_country)), inline = TRUE),
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
   
    d <- d %>% filter(native_country %in% input$native__country)
    
    library(ggplot2)
    
      ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2)
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

## Question 4: Census Density with Slider Input

```{r}
library(tidyverse)
library(shiny)

d = read_csv('adult_modified.csv')


# get variable names
variables_names = names(d)

# get names of numeric variables
variables_numeric = d %>% select_if(is.numeric) %>% names

# get names of categorical variables
variables_category = d %>% select_if(is.character) %>% names


ui <- fluidPage(
  
  titlePanel("Density Plot for Census Data"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variable",
        choices = variables_numeric, selected = "age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variable",
        choices = variables_category,
        selected = "sex"
      ), 
      
      sliderInput(inputId = "Hours",
                  "Select Hours per Week:",
                  min = min(d$hours_per_week, na.rm=TRUE),
                  max = max(d$hours_per_week, na.rm=TRUE),
                  value= c(20, 45))
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
   
    
    library(ggplot2)
    
    d <- d %>% filter(hours_per_week>input$Hours[1], hours_per_week<input$Hours[2])
      
    ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2)
      
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```
